#include "shares.h"
#include "console.h"
#include "ascii.h"
#include "colors.h"

#include <thread>
#include <vector>
#include <iostream>
#include <chrono>
#include <cstdint>
#include <stdio.h>
#include <curl/curl.h>

long Shares = 0;
long Errors = 0;

uint64_t timeSinceEpochMillisec() {
	using namespace std::chrono;
	return duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
}

std::string getRandom()
{
	char array[19];
	for (int i = 1; i <= 19; i++) {
		array[i] = rand() % 10;
	}
	return std::to_string(array[1] + array[2] + array[3] + array[4] + array[5] + array[6] + array[7] + array[8] + array[9] + array[10] + array[11] + array[12] + array[13] + array[14] + array[15] + array[16] + array[17] + array[18] + array[19]);
}

void SendShare(std::string url) {
	while (true) {
		try {
			CURL* curl;
			CURLcode res;

			curl_global_init(CURL_GLOBAL_ALL);
			curl = curl_easy_init();
			
			if (curl) {
				int res = 0;

				std::string api = "https://api31-core-useast1a.tiktokv.com/aweme/v1/aweme/stats/?channel=googleplay&device_type=G011A&device_id=" + getRandom() + "&os_version=7.1.2&version_code=220400&app_name=musically_go&device_platform=android&aid=1988";
				std::string fields = "item_id=" + url + "&share_delta=1";

				struct curl_slist* headers = NULL;
				headers = curl_slist_append(headers, "Content-Type: application/x-www-form-urlencoded");
				headers = curl_slist_append(headers, "User-Agent: com.zhiliaoapp.musically/2022309050 (Linux; U; Android 7.1.2; en; G011A; Build/N2G48H;tt-ok/3.10.0.2");

				curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
				curl_easy_setopt(curl, CURLOPT_URL, api);
				curl_easy_setopt(curl, CURLOPT_POST, 1);
				curl_easy_setopt(curl, CURLOPT_POSTFIELDS, fields);

				res = curl_easy_perform(curl);
				if (res != CURLE_OK) {
				}
				curl_easy_cleanup(curl);
				curl_global_cleanup();
			}

		}
		catch (const std::exception& e) {
		}
	}
}

void CreateSendThreads(std::string VideoUrl) {
	
	std::thread t0(SendShare, VideoUrl);
	std::thread t1(SendShare, VideoUrl);
	std::thread t2(SendShare, VideoUrl);
	std::thread t3(SendShare, VideoUrl);
	std::thread t4(SendShare, VideoUrl);
	std::thread t5(SendShare, VideoUrl);
	std::thread t6(SendShare, VideoUrl);
	std::thread t7(SendShare, VideoUrl);
	std::thread t8(SendShare, VideoUrl);
	std::thread t9(SendShare, VideoUrl);
	std::thread t10(SendShare, VideoUrl);
	std::thread t11(SendShare, VideoUrl);
	std::thread t12(SendShare, VideoUrl);
	std::thread t13(SendShare, VideoUrl);
	std::thread t14(SendShare, VideoUrl);
	std::thread t15(SendShare, VideoUrl);
	std::thread t16(SendShare, VideoUrl);
	std::thread t17(SendShare, VideoUrl);
	std::thread t18(SendShare, VideoUrl);
	std::thread t19(SendShare, VideoUrl);
	std::thread t20(SendShare, VideoUrl);
	std::thread t21(SendShare, VideoUrl);
	std::thread t22(SendShare, VideoUrl);
	std::thread t23(SendShare, VideoUrl);
	std::thread t24(SendShare, VideoUrl);
	std::thread t25(SendShare, VideoUrl);
	std::thread t26(SendShare, VideoUrl);
	std::thread t27(SendShare, VideoUrl);
	std::thread t28(SendShare, VideoUrl);
	std::thread t29(SendShare, VideoUrl);
	std::thread t30(SendShare, VideoUrl);
	std::thread t31(SendShare, VideoUrl);
	std::thread t32(SendShare, VideoUrl);
	std::thread t33(SendShare, VideoUrl);
	std::thread t34(SendShare, VideoUrl);
	std::thread t35(SendShare, VideoUrl);
	std::thread t36(SendShare, VideoUrl);
	std::thread t37(SendShare, VideoUrl);
	std::thread t38(SendShare, VideoUrl);
	std::thread t39(SendShare, VideoUrl);
	std::thread t40(SendShare, VideoUrl);
	std::thread t41(SendShare, VideoUrl);
	std::thread t42(SendShare, VideoUrl);
	std::thread t43(SendShare, VideoUrl);
	std::thread t44(SendShare, VideoUrl);
	std::thread t45(SendShare, VideoUrl);
	std::thread t46(SendShare, VideoUrl);
	std::thread t47(SendShare, VideoUrl);
	std::thread t48(SendShare, VideoUrl);
	std::thread t49(SendShare, VideoUrl);
	std::thread t50(SendShare, VideoUrl);
	std::thread t51(SendShare, VideoUrl);
	std::thread t52(SendShare, VideoUrl);
	std::thread t53(SendShare, VideoUrl);
	std::thread t54(SendShare, VideoUrl);
	std::thread t55(SendShare, VideoUrl);
	std::thread t56(SendShare, VideoUrl);
	std::thread t57(SendShare, VideoUrl);
	std::thread t58(SendShare, VideoUrl);
	std::thread t59(SendShare, VideoUrl);
	std::thread t60(SendShare, VideoUrl);
	std::thread t61(SendShare, VideoUrl);
	std::thread t62(SendShare, VideoUrl);
	std::thread t63(SendShare, VideoUrl);
	std::thread t64(SendShare, VideoUrl);
	std::thread t65(SendShare, VideoUrl);
	std::thread t66(SendShare, VideoUrl);
	std::thread t67(SendShare, VideoUrl);
	std::thread t68(SendShare, VideoUrl);
	std::thread t69(SendShare, VideoUrl);
	std::thread t70(SendShare, VideoUrl);
	std::thread t71(SendShare, VideoUrl);
	std::thread t72(SendShare, VideoUrl);
	std::thread t73(SendShare, VideoUrl);
	std::thread t74(SendShare, VideoUrl);
	std::thread t75(SendShare, VideoUrl);
	std::thread t76(SendShare, VideoUrl);
	std::thread t77(SendShare, VideoUrl);
	std::thread t78(SendShare, VideoUrl);
	std::thread t79(SendShare, VideoUrl);
	std::thread t80(SendShare, VideoUrl);
	std::thread t81(SendShare, VideoUrl);
	std::thread t82(SendShare, VideoUrl);
	std::thread t83(SendShare, VideoUrl);
	std::thread t84(SendShare, VideoUrl);
	std::thread t85(SendShare, VideoUrl);
	std::thread t86(SendShare, VideoUrl);
	std::thread t87(SendShare, VideoUrl);
	std::thread t88(SendShare, VideoUrl);
	std::thread t89(SendShare, VideoUrl);
	std::thread t90(SendShare, VideoUrl);
	std::thread t91(SendShare, VideoUrl);
	std::thread t92(SendShare, VideoUrl);
	std::thread t93(SendShare, VideoUrl);
	std::thread t94(SendShare, VideoUrl);
	std::thread t95(SendShare, VideoUrl);
	std::thread t96(SendShare, VideoUrl);
	std::thread t97(SendShare, VideoUrl);
	std::thread t98(SendShare, VideoUrl);
	std::thread t99(SendShare, VideoUrl);
	std::thread t100(SendShare, VideoUrl);
	std::thread t101(SendShare, VideoUrl);
	std::thread t102(SendShare, VideoUrl);
	std::thread t103(SendShare, VideoUrl);
	std::thread t104(SendShare, VideoUrl);
	std::thread t105(SendShare, VideoUrl);
	std::thread t106(SendShare, VideoUrl);
	std::thread t107(SendShare, VideoUrl);
	std::thread t108(SendShare, VideoUrl);
	std::thread t109(SendShare, VideoUrl);
	std::thread t110(SendShare, VideoUrl);
	std::thread t111(SendShare, VideoUrl);
	std::thread t112(SendShare, VideoUrl);
	std::thread t113(SendShare, VideoUrl);
	std::thread t114(SendShare, VideoUrl);
	std::thread t115(SendShare, VideoUrl);
	std::thread t116(SendShare, VideoUrl);
	std::thread t117(SendShare, VideoUrl);
	std::thread t118(SendShare, VideoUrl);
	std::thread t119(SendShare, VideoUrl);
	std::thread t120(SendShare, VideoUrl);
	std::thread t121(SendShare, VideoUrl);
	std::thread t122(SendShare, VideoUrl);
	std::thread t123(SendShare, VideoUrl);
	std::thread t124(SendShare, VideoUrl);
	std::thread t125(SendShare, VideoUrl);
	std::thread t126(SendShare, VideoUrl);
	std::thread t127(SendShare, VideoUrl);
	std::thread t128(SendShare, VideoUrl);
	std::thread t129(SendShare, VideoUrl);
	std::thread t130(SendShare, VideoUrl);
	std::thread t131(SendShare, VideoUrl);
	std::thread t132(SendShare, VideoUrl);
	std::thread t133(SendShare, VideoUrl);
	std::thread t134(SendShare, VideoUrl);
	std::thread t135(SendShare, VideoUrl);
	std::thread t136(SendShare, VideoUrl);
	std::thread t137(SendShare, VideoUrl);
	std::thread t138(SendShare, VideoUrl);
	std::thread t139(SendShare, VideoUrl);
	std::thread t140(SendShare, VideoUrl);
	std::thread t141(SendShare, VideoUrl);
	std::thread t142(SendShare, VideoUrl);
	std::thread t143(SendShare, VideoUrl);
	std::thread t144(SendShare, VideoUrl);
	std::thread t145(SendShare, VideoUrl);
	std::thread t146(SendShare, VideoUrl);
	std::thread t147(SendShare, VideoUrl);
	std::thread t148(SendShare, VideoUrl);
	std::thread t149(SendShare, VideoUrl);
	std::thread t150(SendShare, VideoUrl);
	std::thread t151(SendShare, VideoUrl);
	std::thread t152(SendShare, VideoUrl);
	std::thread t153(SendShare, VideoUrl);
	std::thread t154(SendShare, VideoUrl);
	std::thread t155(SendShare, VideoUrl);
	std::thread t156(SendShare, VideoUrl);
	std::thread t157(SendShare, VideoUrl);
	std::thread t158(SendShare, VideoUrl);
	std::thread t159(SendShare, VideoUrl);
	std::thread t160(SendShare, VideoUrl);
	std::thread t161(SendShare, VideoUrl);
	std::thread t162(SendShare, VideoUrl);
	std::thread t163(SendShare, VideoUrl);
	std::thread t164(SendShare, VideoUrl);
	std::thread t165(SendShare, VideoUrl);
	std::thread t166(SendShare, VideoUrl);
	std::thread t167(SendShare, VideoUrl);
	std::thread t168(SendShare, VideoUrl);
	std::thread t169(SendShare, VideoUrl);
	std::thread t170(SendShare, VideoUrl);
	std::thread t171(SendShare, VideoUrl);
	std::thread t172(SendShare, VideoUrl);
	std::thread t173(SendShare, VideoUrl);
	std::thread t174(SendShare, VideoUrl);
	std::thread t175(SendShare, VideoUrl);
	std::thread t176(SendShare, VideoUrl);
	std::thread t177(SendShare, VideoUrl);
	std::thread t178(SendShare, VideoUrl);
	std::thread t179(SendShare, VideoUrl);
	std::thread t180(SendShare, VideoUrl);
	std::thread t181(SendShare, VideoUrl);
	std::thread t182(SendShare, VideoUrl);
	std::thread t183(SendShare, VideoUrl);
	std::thread t184(SendShare, VideoUrl);
	std::thread t185(SendShare, VideoUrl);
	std::thread t186(SendShare, VideoUrl);
	std::thread t187(SendShare, VideoUrl);
	std::thread t188(SendShare, VideoUrl);
	std::thread t189(SendShare, VideoUrl);
	std::thread t190(SendShare, VideoUrl);
	std::thread t191(SendShare, VideoUrl);
	std::thread t192(SendShare, VideoUrl);
	std::thread t193(SendShare, VideoUrl);
	std::thread t194(SendShare, VideoUrl);
	std::thread t195(SendShare, VideoUrl);
	std::thread t196(SendShare, VideoUrl);
	std::thread t197(SendShare, VideoUrl);
	std::thread t198(SendShare, VideoUrl);
	std::thread t199(SendShare, VideoUrl);
	std::thread t200(SendShare, VideoUrl);
	std::thread t201(SendShare, VideoUrl);
	std::thread t202(SendShare, VideoUrl);
	std::thread t203(SendShare, VideoUrl);
	std::thread t204(SendShare, VideoUrl);
	std::thread t205(SendShare, VideoUrl);
	std::thread t206(SendShare, VideoUrl);
	std::thread t207(SendShare, VideoUrl);
	std::thread t208(SendShare, VideoUrl);
	std::thread t209(SendShare, VideoUrl);
	std::thread t210(SendShare, VideoUrl);
	std::thread t211(SendShare, VideoUrl);
	std::thread t212(SendShare, VideoUrl);
	std::thread t213(SendShare, VideoUrl);
	std::thread t214(SendShare, VideoUrl);
	std::thread t215(SendShare, VideoUrl);
	std::thread t216(SendShare, VideoUrl);
	std::thread t217(SendShare, VideoUrl);
	std::thread t218(SendShare, VideoUrl);
	std::thread t219(SendShare, VideoUrl);
	std::thread t220(SendShare, VideoUrl);
	std::thread t221(SendShare, VideoUrl);
	std::thread t222(SendShare, VideoUrl);
	std::thread t223(SendShare, VideoUrl);
	std::thread t224(SendShare, VideoUrl);
	std::thread t225(SendShare, VideoUrl);
	std::thread t226(SendShare, VideoUrl);
	std::thread t227(SendShare, VideoUrl);
	std::thread t228(SendShare, VideoUrl);
	std::thread t229(SendShare, VideoUrl);
	std::thread t230(SendShare, VideoUrl);
	std::thread t231(SendShare, VideoUrl);
	std::thread t232(SendShare, VideoUrl);
	std::thread t233(SendShare, VideoUrl);
	std::thread t234(SendShare, VideoUrl);
	std::thread t235(SendShare, VideoUrl);
	std::thread t236(SendShare, VideoUrl);
	std::thread t237(SendShare, VideoUrl);
	std::thread t238(SendShare, VideoUrl);
	std::thread t239(SendShare, VideoUrl);
	std::thread t240(SendShare, VideoUrl);
	std::thread t241(SendShare, VideoUrl);
	std::thread t242(SendShare, VideoUrl);
	std::thread t243(SendShare, VideoUrl);
	std::thread t244(SendShare, VideoUrl);
	std::thread t245(SendShare, VideoUrl);
	std::thread t246(SendShare, VideoUrl);
	std::thread t247(SendShare, VideoUrl);
	std::thread t248(SendShare, VideoUrl);
	std::thread t249(SendShare, VideoUrl);
	std::thread t250(SendShare, VideoUrl);
	std::thread t251(SendShare, VideoUrl);
	std::thread t252(SendShare, VideoUrl);
	std::thread t253(SendShare, VideoUrl);
	std::thread t254(SendShare, VideoUrl);
	std::thread t255(SendShare, VideoUrl);
	std::thread t256(SendShare, VideoUrl);
	std::thread t257(SendShare, VideoUrl);
	std::thread t258(SendShare, VideoUrl);
	std::thread t259(SendShare, VideoUrl);
	std::thread t260(SendShare, VideoUrl);
	std::thread t261(SendShare, VideoUrl);
	std::thread t262(SendShare, VideoUrl);
	std::thread t263(SendShare, VideoUrl);
	std::thread t264(SendShare, VideoUrl);
	std::thread t265(SendShare, VideoUrl);
	std::thread t266(SendShare, VideoUrl);
	std::thread t267(SendShare, VideoUrl);
	std::thread t268(SendShare, VideoUrl);
	std::thread t269(SendShare, VideoUrl);
	std::thread t270(SendShare, VideoUrl);
	std::thread t271(SendShare, VideoUrl);
	std::thread t272(SendShare, VideoUrl);
	std::thread t273(SendShare, VideoUrl);
	std::thread t274(SendShare, VideoUrl);
	std::thread t275(SendShare, VideoUrl);
	std::thread t276(SendShare, VideoUrl);
	std::thread t277(SendShare, VideoUrl);
	std::thread t278(SendShare, VideoUrl);
	std::thread t279(SendShare, VideoUrl);
	std::thread t280(SendShare, VideoUrl);
	std::thread t281(SendShare, VideoUrl);
	std::thread t282(SendShare, VideoUrl);
	std::thread t283(SendShare, VideoUrl);
	std::thread t284(SendShare, VideoUrl);
	std::thread t285(SendShare, VideoUrl);
	std::thread t286(SendShare, VideoUrl);
	std::thread t287(SendShare, VideoUrl);
	std::thread t288(SendShare, VideoUrl);
	std::thread t289(SendShare, VideoUrl);
	std::thread t290(SendShare, VideoUrl);
	std::thread t291(SendShare, VideoUrl);
	std::thread t292(SendShare, VideoUrl);
	std::thread t293(SendShare, VideoUrl);
	std::thread t294(SendShare, VideoUrl);
	std::thread t295(SendShare, VideoUrl);
	std::thread t296(SendShare, VideoUrl);
	std::thread t297(SendShare, VideoUrl);
	std::thread t298(SendShare, VideoUrl);
	std::thread t299(SendShare, VideoUrl);
	std::thread t300(SendShare, VideoUrl);
	std::thread t301(SendShare, VideoUrl);
	std::thread t302(SendShare, VideoUrl);
	std::thread t303(SendShare, VideoUrl);
	std::thread t304(SendShare, VideoUrl);
	std::thread t305(SendShare, VideoUrl);
	std::thread t306(SendShare, VideoUrl);
	std::thread t307(SendShare, VideoUrl);
	std::thread t308(SendShare, VideoUrl);
	std::thread t309(SendShare, VideoUrl);
	std::thread t310(SendShare, VideoUrl);
	std::thread t311(SendShare, VideoUrl);
	std::thread t312(SendShare, VideoUrl);
	std::thread t313(SendShare, VideoUrl);
	std::thread t314(SendShare, VideoUrl);
	std::thread t315(SendShare, VideoUrl);
	std::thread t316(SendShare, VideoUrl);
	std::thread t317(SendShare, VideoUrl);
	std::thread t318(SendShare, VideoUrl);
	std::thread t319(SendShare, VideoUrl);
	std::thread t320(SendShare, VideoUrl);
	std::thread t321(SendShare, VideoUrl);
	std::thread t322(SendShare, VideoUrl);
	std::thread t323(SendShare, VideoUrl);
	std::thread t324(SendShare, VideoUrl);
	std::thread t325(SendShare, VideoUrl);
	std::thread t326(SendShare, VideoUrl);
	std::thread t327(SendShare, VideoUrl);
	std::thread t328(SendShare, VideoUrl);
	std::thread t329(SendShare, VideoUrl);
	std::thread t330(SendShare, VideoUrl);
	std::thread t331(SendShare, VideoUrl);
	std::thread t332(SendShare, VideoUrl);
	std::thread t333(SendShare, VideoUrl);
	std::thread t334(SendShare, VideoUrl);
	std::thread t335(SendShare, VideoUrl);
	std::thread t336(SendShare, VideoUrl);
	std::thread t337(SendShare, VideoUrl);
	std::thread t338(SendShare, VideoUrl);
	std::thread t339(SendShare, VideoUrl);
	std::thread t340(SendShare, VideoUrl);
	std::thread t341(SendShare, VideoUrl);
	std::thread t342(SendShare, VideoUrl);
	std::thread t343(SendShare, VideoUrl);
	std::thread t344(SendShare, VideoUrl);
	std::thread t345(SendShare, VideoUrl);
	std::thread t346(SendShare, VideoUrl);
	std::thread t347(SendShare, VideoUrl);
	std::thread t348(SendShare, VideoUrl);
	std::thread t349(SendShare, VideoUrl);
	std::thread t350(SendShare, VideoUrl);
	std::thread t351(SendShare, VideoUrl);
	std::thread t352(SendShare, VideoUrl);
	std::thread t353(SendShare, VideoUrl);
	std::thread t354(SendShare, VideoUrl);
	std::thread t355(SendShare, VideoUrl);
	std::thread t356(SendShare, VideoUrl);
	std::thread t357(SendShare, VideoUrl);
	std::thread t358(SendShare, VideoUrl);
	std::thread t359(SendShare, VideoUrl);
	std::thread t360(SendShare, VideoUrl);
	std::thread t361(SendShare, VideoUrl);
	std::thread t362(SendShare, VideoUrl);
	std::thread t363(SendShare, VideoUrl);
	std::thread t364(SendShare, VideoUrl);
	std::thread t365(SendShare, VideoUrl);
	std::thread t366(SendShare, VideoUrl);
	std::thread t367(SendShare, VideoUrl);
	std::thread t368(SendShare, VideoUrl);
	std::thread t369(SendShare, VideoUrl);
	std::thread t370(SendShare, VideoUrl);
	std::thread t371(SendShare, VideoUrl);
	std::thread t372(SendShare, VideoUrl);
	std::thread t373(SendShare, VideoUrl);
	std::thread t374(SendShare, VideoUrl);
	std::thread t375(SendShare, VideoUrl);
	std::thread t376(SendShare, VideoUrl);
	std::thread t377(SendShare, VideoUrl);
	std::thread t378(SendShare, VideoUrl);
	std::thread t379(SendShare, VideoUrl);
	std::thread t380(SendShare, VideoUrl);
	std::thread t381(SendShare, VideoUrl);
	std::thread t382(SendShare, VideoUrl);
	std::thread t383(SendShare, VideoUrl);
	std::thread t384(SendShare, VideoUrl);
	std::thread t385(SendShare, VideoUrl);
	std::thread t386(SendShare, VideoUrl);
	std::thread t387(SendShare, VideoUrl);
	std::thread t388(SendShare, VideoUrl);
	std::thread t389(SendShare, VideoUrl);
	std::thread t390(SendShare, VideoUrl);
	std::thread t391(SendShare, VideoUrl);
	std::thread t392(SendShare, VideoUrl);
	std::thread t393(SendShare, VideoUrl);
	std::thread t394(SendShare, VideoUrl);
	std::thread t395(SendShare, VideoUrl);
	std::thread t396(SendShare, VideoUrl);
	std::thread t397(SendShare, VideoUrl);
	std::thread t398(SendShare, VideoUrl);
	std::thread t399(SendShare, VideoUrl);
	std::thread t400(SendShare, VideoUrl);
	std::thread t401(SendShare, VideoUrl);
	std::thread t402(SendShare, VideoUrl);
	std::thread t403(SendShare, VideoUrl);
	std::thread t404(SendShare, VideoUrl);
	std::thread t405(SendShare, VideoUrl);
	std::thread t406(SendShare, VideoUrl);
	std::thread t407(SendShare, VideoUrl);
	std::thread t408(SendShare, VideoUrl);
	std::thread t409(SendShare, VideoUrl);
	std::thread t410(SendShare, VideoUrl);
	std::thread t411(SendShare, VideoUrl);
	std::thread t412(SendShare, VideoUrl);
	std::thread t413(SendShare, VideoUrl);
	std::thread t414(SendShare, VideoUrl);
	std::thread t415(SendShare, VideoUrl);
	std::thread t416(SendShare, VideoUrl);
	std::thread t417(SendShare, VideoUrl);
	std::thread t418(SendShare, VideoUrl);
	std::thread t419(SendShare, VideoUrl);
	std::thread t420(SendShare, VideoUrl);
	std::thread t421(SendShare, VideoUrl);
	std::thread t422(SendShare, VideoUrl);
	std::thread t423(SendShare, VideoUrl);
	std::thread t424(SendShare, VideoUrl);
	std::thread t425(SendShare, VideoUrl);
	std::thread t426(SendShare, VideoUrl);
	std::thread t427(SendShare, VideoUrl);
	std::thread t428(SendShare, VideoUrl);
	std::thread t429(SendShare, VideoUrl);
	std::thread t430(SendShare, VideoUrl);
	std::thread t431(SendShare, VideoUrl);
	std::thread t432(SendShare, VideoUrl);
	std::thread t433(SendShare, VideoUrl);
	std::thread t434(SendShare, VideoUrl);
	std::thread t435(SendShare, VideoUrl);
	std::thread t436(SendShare, VideoUrl);
	std::thread t437(SendShare, VideoUrl);
	std::thread t438(SendShare, VideoUrl);
	std::thread t439(SendShare, VideoUrl);
	std::thread t440(SendShare, VideoUrl);
	std::thread t441(SendShare, VideoUrl);
	std::thread t442(SendShare, VideoUrl);
	std::thread t443(SendShare, VideoUrl);
	std::thread t444(SendShare, VideoUrl);
	std::thread t445(SendShare, VideoUrl);
	std::thread t446(SendShare, VideoUrl);
	std::thread t447(SendShare, VideoUrl);
	std::thread t448(SendShare, VideoUrl);
	std::thread t449(SendShare, VideoUrl);
	std::thread t450(SendShare, VideoUrl);
	std::thread t451(SendShare, VideoUrl);
	std::thread t452(SendShare, VideoUrl);
	std::thread t453(SendShare, VideoUrl);
	std::thread t454(SendShare, VideoUrl);
	std::thread t455(SendShare, VideoUrl);
	std::thread t456(SendShare, VideoUrl);
	std::thread t457(SendShare, VideoUrl);
	std::thread t458(SendShare, VideoUrl);
	std::thread t459(SendShare, VideoUrl);
	std::thread t460(SendShare, VideoUrl);
	std::thread t461(SendShare, VideoUrl);
	std::thread t462(SendShare, VideoUrl);
	std::thread t463(SendShare, VideoUrl);
	std::thread t464(SendShare, VideoUrl);
	std::thread t465(SendShare, VideoUrl);
	std::thread t466(SendShare, VideoUrl);
	std::thread t467(SendShare, VideoUrl);
	std::thread t468(SendShare, VideoUrl);
	std::thread t469(SendShare, VideoUrl);
	std::thread t470(SendShare, VideoUrl);
	std::thread t471(SendShare, VideoUrl);
	std::thread t472(SendShare, VideoUrl);
	std::thread t473(SendShare, VideoUrl);
	std::thread t474(SendShare, VideoUrl);
	std::thread t475(SendShare, VideoUrl);
	std::thread t476(SendShare, VideoUrl);
	std::thread t477(SendShare, VideoUrl);
	std::thread t478(SendShare, VideoUrl);
	std::thread t479(SendShare, VideoUrl);
	std::thread t480(SendShare, VideoUrl);
	std::thread t481(SendShare, VideoUrl);
	std::thread t482(SendShare, VideoUrl);
	std::thread t483(SendShare, VideoUrl);
	std::thread t484(SendShare, VideoUrl);
	std::thread t485(SendShare, VideoUrl);
	std::thread t486(SendShare, VideoUrl);
	std::thread t487(SendShare, VideoUrl);
	std::thread t488(SendShare, VideoUrl);
	std::thread t489(SendShare, VideoUrl);
	std::thread t490(SendShare, VideoUrl);
	std::thread t491(SendShare, VideoUrl);
	std::thread t492(SendShare, VideoUrl);
	std::thread t493(SendShare, VideoUrl);
	std::thread t494(SendShare, VideoUrl);
	std::thread t495(SendShare, VideoUrl);
	std::thread t496(SendShare, VideoUrl);
	std::thread t497(SendShare, VideoUrl);
	std::thread t498(SendShare, VideoUrl);
	std::thread t499(SendShare, VideoUrl);
	std::thread t500(SendShare, VideoUrl);

	t0.join();
	t1.join();
	t2.join();
	t3.join();
	t4.join();
	t5.join();
	t6.join();
	t7.join();
	t8.join();
	t9.join();
	t10.join();
	t11.join();
	t12.join();
	t13.join();
	t14.join();
	t15.join();
	t16.join();
	t17.join();
	t18.join();
	t19.join();
	t20.join();
	t21.join();
	t22.join();
	t23.join();
	t24.join();
	t25.join();
	t26.join();
	t27.join();
	t28.join();
	t29.join();
	t30.join();
	t31.join();
	t32.join();
	t33.join();
	t34.join();
	t35.join();
	t36.join();
	t37.join();
	t38.join();
	t39.join();
	t40.join();
	t41.join();
	t42.join();
	t43.join();
	t44.join();
	t45.join();
	t46.join();
	t47.join();
	t48.join();
	t49.join();
	t50.join();
	t51.join();
	t52.join();
	t53.join();
	t54.join();
	t55.join();
	t56.join();
	t57.join();
	t58.join();
	t59.join();
	t60.join();
	t61.join();
	t62.join();
	t63.join();
	t64.join();
	t65.join();
	t66.join();
	t67.join();
	t68.join();
	t69.join();
	t70.join();
	t71.join();
	t72.join();
	t73.join();
	t74.join();
	t75.join();
	t76.join();
	t77.join();
	t78.join();
	t79.join();
	t80.join();
	t81.join();
	t82.join();
	t83.join();
	t84.join();
	t85.join();
	t86.join();
	t87.join();
	t88.join();
	t89.join();
	t90.join();
	t91.join();
	t92.join();
	t93.join();
	t94.join();
	t95.join();
	t96.join();
	t97.join();
	t98.join();
	t99.join();
	t100.join();
	t101.join();
	t102.join();
	t103.join();
	t104.join();
	t105.join();
	t106.join();
	t107.join();
	t108.join();
	t109.join();
	t110.join();
	t111.join();
	t112.join();
	t113.join();
	t114.join();
	t115.join();
	t116.join();
	t117.join();
	t118.join();
	t119.join();
	t120.join();
	t121.join();
	t122.join();
	t123.join();
	t124.join();
	t125.join();
	t126.join();
	t127.join();
	t128.join();
	t129.join();
	t130.join();
	t131.join();
	t132.join();
	t133.join();
	t134.join();
	t135.join();
	t136.join();
	t137.join();
	t138.join();
	t139.join();
	t140.join();
	t141.join();
	t142.join();
	t143.join();
	t144.join();
	t145.join();
	t146.join();
	t147.join();
	t148.join();
	t149.join();
	t150.join();
	t151.join();
	t152.join();
	t153.join();
	t154.join();
	t155.join();
	t156.join();
	t157.join();
	t158.join();
	t159.join();
	t160.join();
	t161.join();
	t162.join();
	t163.join();
	t164.join();
	t165.join();
	t166.join();
	t167.join();
	t168.join();
	t169.join();
	t170.join();
	t171.join();
	t172.join();
	t173.join();
	t174.join();
	t175.join();
	t176.join();
	t177.join();
	t178.join();
	t179.join();
	t180.join();
	t181.join();
	t182.join();
	t183.join();
	t184.join();
	t185.join();
	t186.join();
	t187.join();
	t188.join();
	t189.join();
	t190.join();
	t191.join();
	t192.join();
	t193.join();
	t194.join();
	t195.join();
	t196.join();
	t197.join();
	t198.join();
	t199.join();
	t200.join();
	t201.join();
	t202.join();
	t203.join();
	t204.join();
	t205.join();
	t206.join();
	t207.join();
	t208.join();
	t209.join();
	t210.join();
	t211.join();
	t212.join();
	t213.join();
	t214.join();
	t215.join();
	t216.join();
	t217.join();
	t218.join();
	t219.join();
	t220.join();
	t221.join();
	t222.join();
	t223.join();
	t224.join();
	t225.join();
	t226.join();
	t227.join();
	t228.join();
	t229.join();
	t230.join();
	t231.join();
	t232.join();
	t233.join();
	t234.join();
	t235.join();
	t236.join();
	t237.join();
	t238.join();
	t239.join();
	t240.join();
	t241.join();
	t242.join();
	t243.join();
	t244.join();
	t245.join();
	t246.join();
	t247.join();
	t248.join();
	t249.join();
	t250.join();
	t251.join();
	t252.join();
	t253.join();
	t254.join();
	t255.join();
	t256.join();
	t257.join();
	t258.join();
	t259.join();
	t260.join();
	t261.join();
	t262.join();
	t263.join();
	t264.join();
	t265.join();
	t266.join();
	t267.join();
	t268.join();
	t269.join();
	t270.join();
	t271.join();
	t272.join();
	t273.join();
	t274.join();
	t275.join();
	t276.join();
	t277.join();
	t278.join();
	t279.join();
	t280.join();
	t281.join();
	t282.join();
	t283.join();
	t284.join();
	t285.join();
	t286.join();
	t287.join();
	t288.join();
	t289.join();
	t290.join();
	t291.join();
	t292.join();
	t293.join();
	t294.join();
	t295.join();
	t296.join();
	t297.join();
	t298.join();
	t299.join();
	t300.join();
	t301.join();
	t302.join();
	t303.join();
	t304.join();
	t305.join();
	t306.join();
	t307.join();
	t308.join();
	t309.join();
	t310.join();
	t311.join();
	t312.join();
	t313.join();
	t314.join();
	t315.join();
	t316.join();
	t317.join();
	t318.join();
	t319.join();
	t320.join();
	t321.join();
	t322.join();
	t323.join();
	t324.join();
	t325.join();
	t326.join();
	t327.join();
	t328.join();
	t329.join();
	t330.join();
	t331.join();
	t332.join();
	t333.join();
	t334.join();
	t335.join();
	t336.join();
	t337.join();
	t338.join();
	t339.join();
	t340.join();
	t341.join();
	t342.join();
	t343.join();
	t344.join();
	t345.join();
	t346.join();
	t347.join();
	t348.join();
	t349.join();
	t350.join();
	t351.join();
	t352.join();
	t353.join();
	t354.join();
	t355.join();
	t356.join();
	t357.join();
	t358.join();
	t359.join();
	t360.join();
	t361.join();
	t362.join();
	t363.join();
	t364.join();
	t365.join();
	t366.join();
	t367.join();
	t368.join();
	t369.join();
	t370.join();
	t371.join();
	t372.join();
	t373.join();
	t374.join();
	t375.join();
	t376.join();
	t377.join();
	t378.join();
	t379.join();
	t380.join();
	t381.join();
	t382.join();
	t383.join();
	t384.join();
	t385.join();
	t386.join();
	t387.join();
	t388.join();
	t389.join();
	t390.join();
	t391.join();
	t392.join();
	t393.join();
	t394.join();
	t395.join();
	t396.join();
	t397.join();
	t398.join();
	t399.join();
	t400.join();
	t401.join();
	t402.join();
	t403.join();
	t404.join();
	t405.join();
	t406.join();
	t407.join();
	t408.join();
	t409.join();
	t410.join();
	t411.join();
	t412.join();
	t413.join();
	t414.join();
	t415.join();
	t416.join();
	t417.join();
	t418.join();
	t419.join();
	t420.join();
	t421.join();
	t422.join();
	t423.join();
	t424.join();
	t425.join();
	t426.join();
	t427.join();
	t428.join();
	t429.join();
	t430.join();
	t431.join();
	t432.join();
	t433.join();
	t434.join();
	t435.join();
	t436.join();
	t437.join();
	t438.join();
	t439.join();
	t440.join();
	t441.join();
	t442.join();
	t443.join();
	t444.join();
	t445.join();
	t446.join();
	t447.join();
	t448.join();
	t449.join();
	t450.join();
	t451.join();
	t452.join();
	t453.join();
	t454.join();
	t455.join();
	t456.join();
	t457.join();
	t458.join();
	t459.join();
	t460.join();
	t461.join();
	t462.join();
	t463.join();
	t464.join();
	t465.join();
	t466.join();
	t467.join();
	t468.join();
	t469.join();
	t470.join();
	t471.join();
	t472.join();
	t473.join();
	t474.join();
	t475.join();
	t476.join();
	t477.join();
	t478.join();
	t479.join();
	t480.join();
	t481.join();
	t482.join();
	t483.join();
	t484.join();
	t485.join();
	t486.join();
	t487.join();
	t488.join();
	t489.join();
	t490.join();
	t491.join();
	t492.join();
	t493.join();
	t494.join();
	t495.join();
	t496.join();
	t497.join();
	t498.join();
	t499.join();
	t500.join();
}